name: Publish release

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.4.0

      - name: Setup .konan cache
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-konan-  

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false

      - name: Extract release version from tag
        run: echo version=$(./version-tag.sh) > version.properties

      - name: Publish to MavenCentral
        run: ./gradlew -Dorg.gradle.jvmargs=-Xmx4g publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.VOXKIT_MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.VOXKIT_MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.VOXKIT_GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.VOXKIT_GPG_PASSWORD }}
